# Generated by Django 5.2.7 on 2025-10-31 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_suggestion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'ordering': ['approved', '-created_at']},
        ),
    ]
